# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

# posts = ":year/:month/:filename"
posts = "posts/:filename"
private = ":sections[1:]/:filename"
