# -------------------------------------------------------------------------------------
# Author Configuration | 作者配置
# -------------------------------------------------------------------------------------

name = "Lruihao"
email = "1024@lruihao.cn"
link = "https://lruihao.cn"
avatar = "/images/avatar.png"
