# -------------------------------------------------------------------------------------
# Multilingual and i18n | 多语言 i18n
# See: https://gohugo.io/content-management/multilingual/#configure-languages
# -------------------------------------------------------------------------------------

[en]
  weight = 1
  # language code
  # 网站语言
  languageCode = "en"
  # language name
  # 语言名称
  languageName = "English"
  # whether to include Chinese/Japanese/Korean
  # 是否包括中日韩文字
  hasCJKLanguage = false
  # copyright description used only for seo schema
  # 版权描述，仅用于 SEO
  copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[zh-cn]
  weight = 2
  # language code, only CN capitalized here
  # 网站语言, 仅在这里 CN 大写
  languageCode = "zh-CN"
  # language name
  # 语言名称
  languageName = "简体中文"
  # whether to include Chinese/Japanese/Korean
  # 是否包括中日韩文字
  hasCJKLanguage = true
  # copyright description used only for seo schema
  # 版权描述，仅用于 SEO
  copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
