# -------------------------------------------------------------------------------------
# Markup related configuration in Hugo | Hugo 解析文档的配置
# See: https://gohugo.io/getting-started/configuration-markup/
# -------------------------------------------------------------------------------------

# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[highlight]
  ######## 必要配置 necessary configurations ########
  # https://github.com/hugo-fixit/FixIt/issues/43
  codeFences = true
  lineNos = true
  lineNumbersInTable = true
  noClasses = false
  ######## 必要配置 necessary configurations ########
  guessSyntax = true

# Goldmark is from Hugo 0.60 the default library used for Markdown
# Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
[goldmark]
  [goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
    wrapStandAloneImageWithinParagraph = true
    [goldmark.parser.attribute]
      block = true
      title = true
  [goldmark.renderer]
    # By default, Goldmark ignores newlines within a paragraph. Set to true to render newlines as <br> elements.
    # 默认情况下，Goldmark 会忽略段落中的换行符。设置为 true 将换行符呈现为 <br> 元素。
    hardWraps = false
    # whether to use HTML tags directly in the document
    # 是否在文档中直接使用 HTML 标签
    unsafe = true

# Table Of Contents settings
# 目录设置
[tableOfContents]
  startLevel = 2
  endLevel = 6
