# -------------------------------------------------------------------------------------
# Media Types | 媒体类型
# See: https://gohugo.io/templates/output-formats/#media-types
# -------------------------------------------------------------------------------------

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
["text/markdown"]
  suffixes = ["md"]

# Options to make output .txt files
# 用于输出 txt 文件的设置
["text/plain"]
  suffixes = ["txt"]
