# -------------------------------------------------------------------------------------
# Menu Configuration | 菜单配置
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "documentation"
  name = "Docs"
  url = "/categories/documentation/"
  title = "Theme Documentation"
  weight = 1
  [main.params]
    icon = "fa-solid fa-book"

[[main]]
  identifier = "faq"
  name = "FAQ"
  url = "faq/"
  weight = 2
  [main.params]
    icon = "fa-solid fa-fire text-danger"

[[main]]
  identifier = "tests"
  name = "Tests"
  url = "tests/"
  title = "Tests for FixIt"
  weight = 3
  [main.params]
    draft = true
    icon = "fa-solid fa-flask text-success"

[[main]]
  identifier = "releases"
  name = "Releases"
  url = "https://github.com/hugo-fixit/FixIt/releases"
  weight = 10
  [main.params]
    type = "desktop"
[[main]]
  identifier = "v0.2.17"
  name = "v0.2.17"
  post = '<i class="fa-solid fa-external-link-alt fa-fw fa-sm text-secondary"></i>'
  url = "https://fixit-pcwilecsu-x-cell.vercel.app"
  parent = "releases"
[[main]]
  identifier = "v0.2.16"
  name = "v0.2.16"
  post = '<i class="fa-solid fa-external-link-alt fa-fw fa-sm text-secondary"></i>'
  url = "https://fixit-jir7e7kzt-x-cell.vercel.app"
  parent = "releases"
[[main]]
  identifier = "v0.2.15"
  name = "v0.2.15"
  post = '<i class="fa-solid fa-external-link-alt fa-fw fa-sm text-secondary"></i>'
  url = "https://fixit-hvd1rg4ba-x-cell.vercel.app"
  parent = "releases"
[[main]]
  identifier = "v0.2.14"
  name = "v0.2.14"
  post = '<i class="fa-solid fa-external-link-alt fa-fw fa-sm text-secondary"></i>'
  url = "https://fixit-p1tg6tsml-lruihao.vercel.app"
  parent = "releases"
[[main]]
  identifier = "v0.2.13"
  name = "v0.2.13"
  post = '<i class="fa-solid fa-external-link-alt fa-fw fa-sm text-secondary"></i>'
  url = "https://fixit-bbh5g5x90-lruihao.vercel.app"
  parent = "releases"
[[main]]
  identifier = "v0.2.12"
  name = "v0.2.12"
  post = '<i class="fa-solid fa-external-link-alt fa-fw fa-sm text-secondary"></i>'
  url = "https://fixit-e9lpwfkbp-lruihao.vercel.app"
  parent = "releases"

[[main]]
  identifier = "about"
  name = "About"
  url = "about/"
  weight = 20
  [main.params]
    icon = "fa-solid fa-info-circle"
[[main]]
  identifier = "friends"
  name = "Friends"
  url = "friends/"
  weight = 21
  parent = "about"
  [main.params]
    icon = "fa-solid fa-users"
[[main]]
  identifier = "guides"
  name = "Guides"
  url = "guides/"
  weight = 22
  parent = "about"
  [main.params]
    icon = "fa-solid fa-layer-group"
[[main]]
  identifier = "references"
  name = "References"
  url = "references/"
  weight = 23
  parent = "about"
  [main.params]
    icon = "fa-solid fa-microchip"
[[main]]
  identifier = "categories"
  name = "Categories"
  url = "categories/"
  parent = "about"
  [main.params]
    icon = "fa-solid fa-th"
[[main]]
  identifier = "tags"
  name = "Tags"
  url = "tags/"
  parent = "about"
  [main.params]
    icon = "fa-solid fa-tags"

[[main]]
  identifier = "github"
  pre = "<i class='fa-brands fa-github fa-fw' aria-hidden='true'></i>"
  url = "https://github.com/hugo-fixit/FixIt"
  title = "GitHub"
  weight = 100
  [main.params]
    class = "text-center"
    type = "mobile"
