# -------------------------------------------------------------------------------------
# Privacy Configuration | 隐私信息配置
# See: https://gohugo.io/about/hugo-and-gdpr/
# -------------------------------------------------------------------------------------

[twitter]
  enableDNT = true

[youtube]
  privacyEnhanced = true
